#!/bin/sh

# Note that code can only test major version.
# Also note that assuming posix shell.
versionmin="6"

# From https://unix.stackexchange.com/a/76518
path=$(exec 2>/dev/null;cd -- $(dirname "$0"); unset PWD; /usr/bin/pwd || /bin/pwd || pwd)

if test "$1" = "test"; then
    # ./hapi-server test
    com="$path/test/server-test.js $@"
else
    # ./hapi-server [server.js args]
    com="$path/server.js $@"
fi

# Use node in path if version > versionmin
if command -v node > /dev/null 2>&1; then
	version=$(node -v)
	version=${version//v/}
	version="${version%%.*}"
    if test $version -gt $(($versionmin-1)); then
    	echo "Using system node binary with version = $version."
		node $com
		exit 0
	else
		echo "System node binary version = $version. Version $versionmin+ required. Using package node binary."
    fi
elif command -v nodejs > /dev/null 2>&1; then
	version=$(node -v)
	version=${version//v/}
	version="${version%%.*}"
    if test $version -gt $(($versionmin-1)); then
    	echo "Using system nodejs binary with version = $version."
		nodejs $com
		exit 0
	else
		echo "System node binary version = $version. Version $versionmin+ required. Using package node binary."
    fi
fi

# Use node in hapi-server package
if command -v $path"/bin/node" > /dev/null 2>&1; then
    $path"/bin/node" $com
else
    echo "Did not find $path/bin/node, node, or nodejs."
    exit 1
fi
